spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8762/eureka
eureka.instance.prefer-ip-address=true

# USER SERVICE ROUTE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# CATALOG SERVICE ROUTE (FIXED 🔥)
spring.cloud.gateway.routes[1].id=catalog-service
spring.cloud.gateway.routes[1].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

logging.level.org.springframework.cloud.gateway=DEBUG